### ISSUE TITLE
InResponseTo validation

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-sp-shibboleth#11]
The following AgID tests will fail without any remediation possibile with a standard shibboleth sp distribution
```
ERROR:spid_sp_test:Test [16] Attributo InResponseTo non specificato. Risultato atteso: KO: : [http status_code: 404] : FAILED
ERROR:spid_sp_test:Test [17] Attributo InResponseTo mancante. Risultato atteso: KO: : [http status_code: 404] : FAILED
ERROR:spid_sp_test:Test [18] Attributo InResponseTo diverso da ID request. Risultato atteso: KO: : [http status_code: 404] : FAILED
```

Here a relevant thread
https://shibboleth.1660669.n2.nabble.com/Validate-InResponseTo-attribute-td7641623.html

**Comment by peppelinux** [comment]
Considerare
https://wiki.shibboleth.net/confluence/display/SP3/CSRF

**Comment by robertogallea** [comment]
Perhaps this can be closed
