### ISSUE TITLE
Validazione AuthnRequest Spid Validator fallita

### ISSUE THREAD

**Issue by Gianluke** [italia/spid-sp-shibboleth#26]
Buonasera,
seguendo quanto descritto nel README, abbiamo installato e configurato Shibboleth SP per accedere all'IDP SPID Validator ma l'AuthnRequest generata non è conforme con quanto descritto nel tag SessionInitiator.
In particolare non vengono generati correttamente:

- "Issuer" (attributi "NameQualifier" e "Format" mancanti)
- "NameIDPolicy" (è presente l'attributo AllowCreate="1")

La versione Shibboleth SP installata è la 3.2.2 (seguendo l'howto riportato su VM CentOS 7.x).
Diversamente da quanto compare nella GIF a corredo, in qui l'AuthnRequest sembra conforme a quanto richiesto da AGID, quella generata dalla nostra installazione risulta differente:
`<saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">
        https://TEST/sp
    </saml:Issuer>
    <samlp:NameIDPolicy AllowCreate="1" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>`

La problematica sembra simile a quanto riportato qui: https://shibboleth.1660669.n2.nabble.com/Modify-tag-issuer-in-LogoutRequest-td7629320.html.

Grazie.

**Comment by robertogallea** [comment]
Salve,
hai usato la stessa configurazione riportata nel repo, o hai fatto personalizzazioni? Attualmente a me la `AuthnRequest` risulta ben formata sia su ShibSP 3.2.0 che su 3.0.4

**Comment by Gianluke** [comment]
Buongiorno Roberto,
come discusso su Slack, il problema era dovuto alla configurazione del nostro discovery service in shibboleth2.xml.
In soldoni non va utilizzata la configurazione seguente:
`<SSO discoveryProtocol="SAMLDS" discoveryURL="https://HOST/discovery-service/WAYF">
  SAML2 SAML1
</SSO>`
ma è necessario aggiungere i riferimenti al DS nella chain del SessionInitiator:
`<SessionInitiator type="SAMLDS" URL="{{DS_URL}}"  signing="true"  forceAuthn="true">
</SessionInitiator>`

Grazie ancora.
