### ISSUE TITLE
xmlns shibboleth version

### ISSUE THREAD

**Issue by wavewa** [italia/spid-sp-shibboleth#8]
Ciao modificando nel mio file shibboleth2.xml  da `<SPConfig xmlns="urn:mace:shibboleth:2.0:native:sp:config"
    xmlns:conf="urn:mace:shibboleth:2.0:native:sp:config"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" 
    xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" clockSkew="180">` a  `<SPConfig xmlns="urn:mace:shibboleth:3.0:native:sp:config"
    xmlns:conf="urn:mace:shibboleth:3.0:native:sp:config"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" 
    xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" clockSkew="180">`, accedendo con al mio sp con la url del validatore locale ho il seguente errore:

`Unable to locate metadata for identity provider (http://localhost:8080)`

**Comment by peppelinux** [comment]
Aggiungi qui
https://github.com/italia/spid-sp-shibboleth/blob/fd98d4296c17556736c1a54ae401591d53600598/shibboleth2.xml#L110

la definizione del metadata di spid-saml-check

**Comment by wavewa** [comment]
Salve, il problema era che nel  <MetadataProvider> la versione precedente che avevo c'era file e non path. Grazie
